// <auto-generated />
namespace TZ_EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Productv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Productv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911151419017_Product-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
