// <auto-generated />
namespace TZ_EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class OrdersAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdersAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201911160849332_OrdersAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
